[changelog]
body = """

<img src="https://raw.githubusercontent.com/rinlit-233-shiroko/class-widgets-2/main/docs/assets/release_banner.png" width="100%" />

> [!WARNING]
> ç›®å‰ Class Widgets 2 ä»ç„¶å¤„äºå¼€å‘é˜¶æ®µï¼Œå¯èƒ½ä¸é€‚ç”¨äºç”Ÿäº§ç¯å¢ƒã€‚
> æ¬¢è¿åé¦ˆæ„è§å’Œå»ºè®®è°¢è°¢å–µ

## Class Widgets 2 æ›´æ–°é€Ÿé€’
> [!NOTE]
> å½“å‰ç‰ˆæœ¬ï¼š`{% if version %}({{ version }}){%- endif -%}`

{% for group, commits in commits | group_by(attribute="group") %}

{% if group != "âœ¨ æ–°äº®ç‚¹" %}
<details>
<summary><h3>{{ group | upper_first }}</h3></summary>
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} ä½œè€…: @{{ commit.remote.username }}{%- endif -%}
  {% if commit.remote.pr_number %} åœ¨ \
[#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
{%- endif %}
{% endfor %}
</details>
{% else %}
### {{ group | upper_first }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {%- endif -%}{{ commit.message | upper_first }}\
  {% if commit.remote.username %} ä½œè€…: @{{ commit.remote.username }}{%- endif -%}
  {% if commit.remote.pr_number %} åœ¨ \
[#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
{%- endif %}
{% endfor %}
{% endif %}

{% endfor -%}

{% if version %}
  {% if previous.version %}
**å®Œæ•´ Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
  {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/rinlit-233-shiroko/class-widgets-2
{%- endmacro -%}

> [!TIP]
> å¯¹äºä¸æ–¹ä¾¿ä½¿ç”¨ GitHub çš„ç”¨æˆ·ï¼Œæ¬¢è¿ä½¿ç”¨ 123 ç½‘ç›˜å’Œ OneDrive æ¥ä¸‹è½½æµ‹è¯•ç‰ˆæœ¬  
> [123 ç½‘ç›˜ä¸‹è½½](https://www.123912.com/s/DCyBTd-3iWxH) ï¼ˆæ— å¯†ç ï¼Œä»¥åçš„æµ‹è¯•ç‰ˆä¹Ÿä¼šæŒç»­åŒæ­¥è‡³æœ¬é“¾ï¼‰  
> [OneDrive ä¸‹è½½](https://dl.gemen.pp.ua)

"""
trim = true
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"


[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "âœ¨ æ–°äº®ç‚¹"},
    { message = "^fix", group = "ğŸ› ï¸ ä¿®å¤çš„é—®é¢˜"},
    { message = "^refactor", group = "ğŸ”ƒ åŠŸèƒ½é‡æ„"},
    { message = "^docs", group = "ğŸ“„ æ–‡æ¡£æ›´æ–°"},
    { message = "^style", group = "ğŸï¸ æ ·å¼ä¼˜åŒ–"},
]
protect_breaking_commits = false
filter_commits = true
topo_order = false
sort_commits = "oldest"
link_parsers = []
