name: Build & Release ClassWidgets-2

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      upload2webdav:
        description: 'Upload to...'
        required: true
        default: 'None'
        type: choice
        options:
          - None
          - 123Pan
          - OneDrive
          - Both
      release:
        description: 'Create GitHub Release'
        required: true
        default: false
        type: boolean
      prerelease:
        description: 'Mark as Pre-release'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-15-intel, macos-latest]

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v5

      - name: üì¶ Set up Python & Install uv
        uses: astral-sh/setup-uv@v6

      - name: üì¶ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ github.workflow }}-

      - name: üì¶ Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller

      - name: üî® Build ClassWidgets-2 (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          uv run pyinstaller --noconsole \
            --icon "assets/images/logo.ico" \
            --add-data "src/qml:src/qml" \
            --add-data "src/plugins:src/plugins" \
            --add-data "assets:assets" \
            --add-data "LICENSE:." \
            --paths=. \
            --contents-directory . \
            --name="Class Widgets 2" \
            src/app.py

      - name: üî® Build ClassWidgets-2 (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          uv run pyinstaller --noconsole \
            --icon "assets/images/logo.icns" \
            --add-data "src/qml:src/qml" \
            --add-data "src/plugins:src/plugins" \
            --add-data "assets:assets" \
            --add-data "LICENSE:." \
            --paths=. \
            --contents-directory . \
            --name="Class Widgets 2" \
            src/app.py

      - name: üì¶ Zip build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/Class Widgets 2/*" -DestinationPath "dist/ClassWidgets-2-Windows.zip"

      - name: üì¶ Zip build (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          hdiutil create -volname "Class Widgets 2" -srcfolder dist -ov -format UDZO ClassWidgets-2-macOS-${{ runner.arch }}.dmg
        # ditto -c -k --sequesterRsrc --keepParent "Class Widgets 2".app ClassWidgets-2-macOS-${{ runner.arch }}.zip

      - name: ‚òÅÔ∏è Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ClassWidgets-2-Windows
          path: dist/ClassWidgets-2-Windows.zip

      - name: ‚òÅÔ∏è Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ClassWidgets-2-macOS-${{ runner.arch }}
          path: ClassWidgets-2-macOS-${{ runner.arch }}.dmg

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ‚¨áÔ∏è Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist/
          merge-multiple: true

      - name: üß± Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: üìú Generate CHANGELOG.md
        run: |
          git cliff --latest --tag "${{ github.ref_name }}" --config .git-cliff.toml > CHANGELOG.md

      - name: üöÄ Create GitHub Release
        uses: softprops/action-gh-release@v2
        # Êé®ÈÄÅ/ÊâãÂä®+ÂèëÂ∏É ==> ÂèëÂ∏É
        if: ${{  github.event_name == 'push' || github.event.inputs.release == 'true' }}
        with:
          name: Class Widgets ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          prerelease: ${{ github.event_name == 'push' || github.event.inputs.prerelease }}
          files: |
            dist/ClassWidgets-2-Windows.zip
            dist/ClassWidgets-2-macOS-X64.dmg
            dist/ClassWidgets-2-macOS-ARM64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      - name: üì§ Upload CHANGELOG & packages to 123Pan
        # Êé®ÈÄÅ/ÊâãÂä®+‰∏ä‰º† ==> ‰∏ä‰º†
        if: success() && 
          ( github.event_name == 'push' ||
           github.event.inputs.upload2webdav == '123Pan' ||
           github.event.inputs.upload2webdav == 'Both')
        run: |
          VERSION="${{ github.ref_name }}"
          ENCODED_VERSION=$(echo "$VERSION" | sed 's/ /%20/g')

          # Create directory
          curl -v -u "${{ secrets.PAN_USER }}:${{ secrets.PAN_PASS }}" \
               -X MKCOL "https://webdav.123pan.cn/webdav/${ENCODED_VERSION}"

          # Upload files
          curl -u "${{ secrets.PAN_USER }}:${{ secrets.PAN_PASS }}" \
            -T "CHANGELOG.md" \
            "https://webdav.123pan.cn/webdav/${ENCODED_VERSION}/CHANGELOG.md"

          curl -u "${{ secrets.PAN_USER }}:${{ secrets.PAN_PASS }}" \
            -T "dist/ClassWidgets-2-Windows.zip" \
            "https://webdav.123pan.cn/webdav/${ENCODED_VERSION}/ClassWidgets-2-Windows.zip"

          curl -u "${{ secrets.PAN_USER }}:${{ secrets.PAN_PASS }}" \
            -T "dist/ClassWidgets-2-macOS-X64.dmg" \
            "https://webdav.123pan.cn/webdav/${ENCODED_VERSION}/ClassWidgets-2-macOS-X64.dmg"
          curl -u "${{ secrets.PAN_USER }}:${{ secrets.PAN_PASS }}" \
            -T "dist/ClassWidgets-2-macOS-ARM64.dmg" \
            "https://webdav.123pan.cn/webdav/${ENCODED_VERSION}/ClassWidgets-2-macOS-ARM64.dmg"

      - name: üîî Trigger Update Class Widgets 2 Releases JSON
        if: success()  # Âè™ÊúâÂâçÈù¢ÊàêÂäüÊâçËß¶Âèë
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/RinLit-233-shiroko/Class-Widgets-2/dispatches \
            -d '{"event_type": "update-version"}'

      - name: üì§ Upload CHANGELOG & packages to OneDrive
        if: success() &&
          (github.event_name == 'push' ||
          github.event.inputs.upload2webdav == 'OneDrive' ||
          github.event.inputs.upload2webdav == 'Both')
        run: |
          VERSION="${{ github.ref_name }}"
          ENCODED_VERSION=$(echo "$VERSION" | sed 's/ /%20/g')

          # Create directory
          curl -v -u "${{ secrets.ONEDRIVE_USER }}:${{ secrets.ONEDRIVE_PASS }}" \
               -X MKCOL "https://app.koofr.net/dav/1Drv/Class-Widgets/${ENCODED_VERSION}"

          # Upload files
          curl -u "${{ secrets.ONEDRIVE_USER }}:${{ secrets.ONEDRIVE_PASS }}" \
            -T "CHANGELOG.md" \
            "https://app.koofr.net/dav/1Drv/Class-Widgets/${ENCODED_VERSION}/CHANGELOG.md"

          curl -u "${{ secrets.ONEDRIVE_USER }}:${{ secrets.ONEDRIVE_PASS }}" \
            -T "dist/ClassWidgets-2-Windows.zip" \
            "https://app.koofr.net/dav/1Drv/Class-Widgets/${ENCODED_VERSION}/ClassWidgets-2-Windows.zip"

          curl -u "${{ secrets.ONEDRIVE_USER }}:${{ secrets.ONEDRIVE_PASS }}" \
            -T "dist/ClassWidgets-2-macOS-X64.dmg" \
            "https://app.koofr.net/dav/1Drv/Class-Widgets/${ENCODED_VERSION}/ClassWidgets-2-macOS-X64.dmg"
          curl -u "${{ secrets.ONEDRIVE_USER }}:${{ secrets.ONEDRIVE_PASS }}" \
            -T "dist/ClassWidgets-2-macOS-ARM64.dmg" \
            "https://app.koofr.net/dav/1Drv/Class-Widgets/${ENCODED_VERSION}/ClassWidgets-2-macOS-ARM64.dmg"
